import type { SpellingErrorItem } from "./types";

export const spellingErrorItems: SpellingErrorItem[] = [
  { id: "se-01", word: "kahvila",        hasError: false },
  { id: "se-02", word: "puurro",         hasError: true  },
  { id: "se-03", word: "perjantai",      hasError: false },
  { id: "se-04", word: "maitto",         hasError: true  },
  { id: "se-05", word: "mansikka",       hasError: false },
  { id: "se-06", word: "takkki",         hasError: true  },
  { id: "se-07", word: "aurinko",        hasError: false },
  { id: "se-08", word: "silmmä",         hasError: true  },
  { id: "se-09", word: "valkoinen",      hasError: false },
  { id: "se-10", word: "lauku",          hasError: true  },
  { id: "se-11", word: "kaappi",         hasError: false },
  { id: "se-12", word: "appelsini",      hasError: true  },
  { id: "se-13", word: "puuro",          hasError: false },
  { id: "se-14", word: "ystäva",         hasError: true  },
  { id: "se-15", word: "laukku",         hasError: false },
  { id: "se-16", word: "pakanen",        hasError: true  },
  { id: "se-17", word: "appelsiini",     hasError: false },
  { id: "se-18", word: "kaupungki",      hasError: true  },
  { id: "se-19", word: "ystävä",         hasError: false },
  { id: "se-20", word: "kappi",          hasError: true  },
  { id: "se-21", word: "pakkanen",       hasError: false },
  { id: "se-22", word: "ikunna",         hasError: true  },
  { id: "se-23", word: "maito",          hasError: false },
  { id: "se-24", word: "keittio",        hasError: true  },
  { id: "se-25", word: "takki",          hasError: false },
  { id: "se-26", word: "kirjaasto",      hasError: true  },
  { id: "se-27", word: "ikkuna",         hasError: false },
  { id: "se-28", word: "jarvi",          hasError: true  },
  { id: "se-29", word: "silmä",          hasError: false },
  { id: "se-30", word: "mansika",        hasError: true  },
  { id: "se-31", word: "keittiö",        hasError: false },
  { id: "se-32", word: "aurinnko",       hasError: true  },
  { id: "se-33", word: "kirjasto",       hasError: false },
  { id: "se-34", word: "valkonen",       hasError: true  },
  { id: "se-35", word: "koulu",          hasError: false },
  { id: "se-36", word: "lenttokenttä",   hasError: true  },
  { id: "se-37", word: "juna",           hasError: false },
  { id: "se-38", word: "postti",         hasError: true  },
  { id: "se-39", word: "pyöräilijä",     hasError: false },
  { id: "se-40", word: "koullu",         hasError: true  },
];
