import type { MinimalPairItem } from "./types";

export const minimalPairItems: MinimalPairItem[] = [
  {
    id: "mp-1",
    sentence: "Puutarhasta löytyi iso ____.",
    optionA: "mato",
    optionB: "matto",
    correctAnswer: "mato",
    type: "consonant length",
  },
  {
    id: "mp-2",
    sentence: "Talon ____ vuotaa pahasti.",
    optionA: "katto",
    optionB: "kato",
    correctAnswer: "katto",
    type: "consonant length",
  },
  {
    id: "mp-3",
    sentence: "Nuotiosta nousi korkea ____.",
    optionA: "tuli",
    optionB: "tuuli",
    correctAnswer: "tuli",
    type: "vowel length",
  },
  {
    id: "mp-4",
    sentence: "Hän heitti ____ maahan.",
    optionA: "palo",
    optionB: "pallo",
    correctAnswer: "pallo",
    type: "consonant length",
  },
  {
    id: "mp-5",
    sentence: "Minun on ____ lähteä nyt.",
    optionA: "pako",
    optionB: "pakko",
    correctAnswer: "pakko",
    type: "consonant length",
  },
  {
    id: "mp-6",
    sentence: "Naapurilla on söpö musta ____.",
    optionA: "kissa",
    optionB: "kisa",
    correctAnswer: "kissa",
    type: "consonant length",
  },
  {
    id: "mp-7",
    sentence: "Hänellä on päässä punainen ____.",
    optionA: "laki",
    optionB: "lakki",
    correctAnswer: "lakki",
    type: "consonant length",
  },
  {
    id: "mp-8",
    sentence: "Meillä on vanha ____ kokoontua jouluna.",
    optionA: "tapa",
    optionB: "tappaa",
    correctAnswer: "tapa",
    type: "consonant length",
  },
  {
    id: "mp-9",
    sentence: "Ulkona alkoi ____.",
    optionA: "sata",
    optionB: "sataa",
    correctAnswer: "sataa",
    type: "vowel length",
  },
  {
    id: "mp-10",
    sentence: "Hän ____ auttaa minua huomenna.",
    optionA: "lupa",
    optionB: "lupaa",
    correctAnswer: "lupaa",
    type: "vowel length",
  },
  {
    id: "mp-11",
    sentence: "Kynttilä ____ hiljaa pöydällä.",
    optionA: "pala",
    optionB: "palaa",
    correctAnswer: "palaa",
    type: "vowel length",
  },
  {
    id: "mp-12",
    sentence: "Talvella lämmin ____ maistuu hyvältä.",
    optionA: "puro",
    optionB: "puuro",
    correctAnswer: "puuro",
    type: "vowel length",
  },
  {
    id: "mp-13",
    sentence: "Tämän tuotteen ____ on erinomainen.",
    optionA: "latu",
    optionB: "laatu",
    correctAnswer: "laatu",
    type: "vowel length",
  },
  {
    id: "mp-14",
    sentence: "Heillä on suuri ____.",
    optionA: "suku",
    optionB: "sukka",
    correctAnswer: "suku",
    type: "consonant length",
  },
  {
    id: "mp-15",
    sentence: "Pöydällä oli kypsä ____.",
    optionA: "kivi",
    optionB: "kiivi",
    correctAnswer: "kiivi",
    type: "vowel length",
  },
];
