import type { SyllableItem } from "./types";

function makeId(prefix: string, n: number) {
  return `${prefix}-${n}`;
}

export const syllableItems: SyllableItem[] = [
  // Level 1: 2 syllables
  {
    id: makeId("l1", 1),
    type: "real",
    level: 1,
    correctWord: "kukka",
    syllablesCorrect: ["kuk", "ka"],
    tiles: [
      { id: "t1", value: "kuk", isDecoy: false },
      { id: "t2", value: "ka", isDecoy: false },
      { id: "t3", value: "kukk", isDecoy: true },
      { id: "t4", value: "ku", isDecoy: true },
    ],
    expectedSyllableCount: 2,
    tags: ["double_consonant"],
  },
  {
    id: makeId("l1", 2),
    type: "real",
    level: 1,
    correctWord: "talo",
    syllablesCorrect: ["ta", "lo"],
    tiles: [
      { id: "t1", value: "ta", isDecoy: false },
      { id: "t2", value: "lo", isDecoy: false },
      { id: "t3", value: "tal", isDecoy: true },
      { id: "t4", value: "taa", isDecoy: true },
    ],
    expectedSyllableCount: 2,
    tags: ["vowel_length"],
  },
  {
    id: makeId("l1", 3),
    type: "pseudo",
    level: 1,
    correctWord: "mipu",
    syllablesCorrect: ["mi", "pu"],
    tiles: [
      { id: "t1", value: "mi", isDecoy: false },
      { id: "t2", value: "pu", isDecoy: false },
      { id: "t3", value: "mip", isDecoy: true },
      { id: "t4", value: "puu", isDecoy: true },
    ],
    expectedSyllableCount: 2,
    tags: ["vowel_length"],
  },
  {
    id: makeId("l1", 4),
    type: "real",
    level: 1,
    correctWord: "pappa",
    syllablesCorrect: ["pap", "pa"],
    tiles: [
      { id: "t1", value: "pap", isDecoy: false },
      { id: "t2", value: "pa", isDecoy: false },
      { id: "t3", value: "pa", isDecoy: true },
      { id: "t4", value: "papp", isDecoy: true },
    ],
    expectedSyllableCount: 2,
    tags: ["double_consonant"],
  },
  {
    id: makeId("l1", 5),
    type: "pseudo",
    level: 1,
    correctWord: "sate",
    syllablesCorrect: ["sa", "te"],
    tiles: [
      { id: "t1", value: "sa", isDecoy: false },
      { id: "t2", value: "te", isDecoy: false },
      { id: "t3", value: "sat", isDecoy: true },
      { id: "t4", value: "tett", isDecoy: true },
    ],
    expectedSyllableCount: 2,
    tags: ["double_consonant"],
  },

  // Level 2: 3 syllables
  {
    id: makeId("l2", 1),
    type: "real",
    level: 2,
    correctWord: "katto",
    syllablesCorrect: ["kat", "to"],
    tiles: [
      { id: "t1", value: "kat", isDecoy: false },
      { id: "t2", value: "to", isDecoy: false },
      { id: "t3", value: "katt", isDecoy: true },
      { id: "t4", value: "ka", isDecoy: true },
    ],
    expectedSyllableCount: 2,
    tags: ["double_consonant"],
  },
  {
    id: makeId("l2", 2),
    type: "real",
    level: 2,
    correctWord: "tuuli",
    syllablesCorrect: ["tuu", "li"],
    tiles: [
      { id: "t1", value: "tuu", isDecoy: false },
      { id: "t2", value: "li", isDecoy: false },
      { id: "t3", value: "tu", isDecoy: true },
      { id: "t4", value: "lil", isDecoy: true },
    ],
    expectedSyllableCount: 2,
    tags: ["vowel_length"],
  },
  {
    id: makeId("l2", 3),
    type: "real",
    level: 2,
    correctWord: "omena",
    syllablesCorrect: ["o", "me", "na"],
    tiles: [
      { id: "t1", value: "o", isDecoy: false },
      { id: "t2", value: "me", isDecoy: false },
      { id: "t3", value: "na", isDecoy: false },
      { id: "t4", value: "men", isDecoy: true },
      { id: "t5", value: "naa", isDecoy: true },
    ],
    expectedSyllableCount: 3,
    tags: [],
  },
  {
    id: makeId("l2", 4),
    type: "pseudo",
    level: 2,
    correctWord: "pilota",
    syllablesCorrect: ["pi", "lo", "ta"],
    tiles: [
      { id: "t1", value: "pi", isDecoy: false },
      { id: "t2", value: "lo", isDecoy: false },
      { id: "t3", value: "ta", isDecoy: false },
      { id: "t4", value: "lott", isDecoy: true },
      { id: "t5", value: "taa", isDecoy: true },
    ],
    expectedSyllableCount: 3,
    tags: ["double_consonant", "vowel_length"],
  },
  {
    id: makeId("l2", 5),
    type: "real",
    level: 2,
    correctWord: "kissa",
    syllablesCorrect: ["kis", "sa"],
    tiles: [
      { id: "t1", value: "kis", isDecoy: false },
      { id: "t2", value: "sa", isDecoy: false },
      { id: "t3", value: "kiss", isDecoy: true },
      { id: "t4", value: "saa", isDecoy: true },
    ],
    expectedSyllableCount: 2,
    tags: ["double_consonant", "vowel_length"],
  },

  // Level 3: 4 syllables
  {
    id: makeId("l3", 1),
    type: "real",
    level: 3,
    correctWord: "tavoitella",
    syllablesCorrect: ["ta", "voi", "tel", "la"],
    tiles: [
      { id: "t1", value: "ta", isDecoy: false },
      { id: "t2", value: "voi", isDecoy: false },
      { id: "t3", value: "tel", isDecoy: false },
      { id: "t4", value: "la", isDecoy: false },
      { id: "t5", value: "tatt", isDecoy: true },
      { id: "t6", value: "laa", isDecoy: true },
    ],
    expectedSyllableCount: 4,
    tags: ["double_consonant", "vowel_length"],
  },
  {
    id: makeId("l3", 2),
    type: "pseudo",
    level: 3,
    correctWord: "satalo",
    syllablesCorrect: ["sa", "ta", "lo"],
    tiles: [
      { id: "t1", value: "sa", isDecoy: false },
      { id: "t2", value: "ta", isDecoy: false },
      { id: "t3", value: "lo", isDecoy: false },
      { id: "t4", value: "satt", isDecoy: true },
      { id: "t5", value: "taa", isDecoy: true },
    ],
    expectedSyllableCount: 3,
    tags: ["double_consonant", "vowel_length"],
  },
  {
    id: makeId("l3", 3),
    type: "real",
    level: 3,
    correctWord: "tavata",
    syllablesCorrect: ["ta", "va", "ta"],
    tiles: [
      { id: "t1", value: "ta", isDecoy: false },
      { id: "t2", value: "va", isDecoy: false },
      { id: "t3", value: "ta", isDecoy: false },
      { id: "t4", value: "tatt", isDecoy: true },
      { id: "t5", value: "vaa", isDecoy: true },
    ],
    expectedSyllableCount: 3,
    tags: ["double_consonant", "vowel_length"],
  },

  // Level 4: 5+ syllables
  {
    id: makeId("l4", 1),
    type: "real",
    level: 4,
    correctWord: "tavoitellaan",
    syllablesCorrect: ["ta", "voi", "tel", "laan"],
    tiles: [
      { id: "t1", value: "ta", isDecoy: false },
      { id: "t2", value: "voi", isDecoy: false },
      { id: "t3", value: "tel", isDecoy: false },
      { id: "t4", value: "laan", isDecoy: false },
      { id: "t5", value: "va", isDecoy: true },
      { id: "t6", value: "laa", isDecoy: true },
    ],
    expectedSyllableCount: 4,
    tags: ["vowel_length"],
  },
  {
    id: makeId("l4", 2),
    type: "pseudo",
    level: 4,
    correctWord: "kuppatalo",
    syllablesCorrect: ["kup", "pa", "ta", "lo"],
    tiles: [
      { id: "t1", value: "kup", isDecoy: false },
      { id: "t2", value: "pa", isDecoy: false },
      { id: "t3", value: "ta", isDecoy: false },
      { id: "t4", value: "lo", isDecoy: false },
      { id: "t5", value: "kupp", isDecoy: true },
      { id: "t6", value: "paa", isDecoy: true },
    ],
    expectedSyllableCount: 4,
    tags: ["double_consonant", "vowel_length"],
  },
];
