import type { SyllableItem } from "./types";

export const syllableItems: SyllableItem[] = [
  { id: "s1",  syllables: ["lois", "te", "lias"],           correctWord: "loistelias" },
  { id: "s2",  syllables: ["kat", "so", "jat"],             correctWord: "katsojat" },
  { id: "s4",  syllables: ["sa", "dun", "omai", "nen"],     correctWord: "sadunomainen" },
  { id: "s5",  syllables: ["pää", "hen", "ki", "lö"],       correctWord: "päähenkilö" },
  { id: "s7",  syllables: ["vai", "heik", "kai", "den"],    correctWord: "vaiheikkaiden" },
  { id: "s8",  syllables: ["ul", "ko", "maa", "lai", "se", "na"], correctWord: "ulkomaalaisena" },
  { id: "s9",  syllables: ["kir", "jas", "to"],             correctWord: "kirjasto" },
  { id: "s10", syllables: ["au", "rin", "ko"],              correctWord: "aurinko" },
  { id: "s11", syllables: ["tal", "vi", "nen"],             correctWord: "talvinen" },
  { id: "s12", syllables: ["puu", "tar", "ha"],             correctWord: "puutarha" },
  { id: "s13", syllables: ["sa", "teel", "la"],             correctWord: "sateella" },
  { id: "s14", syllables: ["kau", "pun", "ki"],             correctWord: "kaupunki" },
  { id: "s15", syllables: ["lii", "ken", "ne"],             correctWord: "liikenne" },
  { id: "s16", syllables: ["ys", "tä", "väl", "li", "nen"],correctWord: "ystävällinen" },
  { id: "s17", syllables: ["maa", "il", "man"],             correctWord: "maailman" },
  { id: "s18", syllables: ["kou", "lu", "tus"],             correctWord: "koulutus" },
  { id: "s19", syllables: ["ter", "vey", "den", "hoi", "to"], correctWord: "terveydenhoito" },
  { id: "s20", syllables: ["tut", "ki", "mus"],             correctWord: "tutkimus" },
  { id: "s21", syllables: ["kir", "joit", "ta", "mi", "nen"], correctWord: "kirjoittaminen" },
  { id: "s22", syllables: ["lu", "ke", "mi", "nen"],        correctWord: "lukeminen" },
  { id: "s23", syllables: ["op", "pi", "mi", "nen"],        correctWord: "oppiminen" },
  { id: "s24", syllables: ["ym", "mär", "tä", "mi", "nen"],correctWord: "ymmärtäminen" },
  { id: "s25", syllables: ["vas", "taa", "mi", "nen"],      correctWord: "vastaaminen" },
  { id: "s26", syllables: ["muis", "ta", "mi", "nen"],      correctWord: "muistaminen" },
  { id: "s27", syllables: ["ha", "vait", "se", "mi", "nen"], correctWord: "havaitseminen" },
  { id: "s28", syllables: ["ver", "tai", "le", "mi", "nen"], correctWord: "vertaileminen" },
];
